### ISSUE TITLE
菜鸡求问

### ISSUE THREAD

**Issue by zoor-creator** [EggUncle/GiikerDesktopClient#1]
自己的地址这些要怎么知道啊

**Comment by EggUncle** [comment]
我还真忘了。。。你可以找找相关蓝牙信息获取的app之类的，android上这类应用应该挺多的，里面应该是能找到相关信息的。如果魔方在广播寻求链接设备的时候，理论上包里面也有这类信息，不过需要专业一些的应用才能看到。
